services:

  postgres:
    image: postgres:13
    restart: on-failure
    environment:
      - 'POSTGRES_DB=tasks_db'
      - 'POSTGRES_USER=tasks_admin'
      - 'POSTGRES_PASSWORD=tasks_password'
    ports:
      - '5432:5432'


  rabbitmq:
    image: rabbitmq:4.0-management
    restart: on-failure
    environment:
      - 'RABBITMQ_DEFAULT_USER: user'
      - 'RABBITMQ_DEFAULT_PASS: password'
    ports:
      - "5672:5672"
      - "15672:15672"